### ISSUE TITLE
Can't call --help when there is any required flags

### ISSUE THREAD

**Issue by relonger** [jwaldrip/admiral.cr#1]
define_help description: "Generate SQL files to load content data to DB"
   define_flag account_id : Int32, required: true, description: "Account ID to process"

Calling with --help gives:

```
Flag: --account-id is required (Admiral::Error)
0x10fdec935: *CallStack::unwind:Array(Pointer(Void)) at ??
0x10fdec8d1: *CallStack#initialize:Array(Pointer(Void)) at ??
0x10fdec8a8: *CallStack::new:CallStack at ??
0x10fde93d1: *raise<Admiral::Error>:NoReturn at ??
```

Setting required: false solves the issue, but requires extra manual check on command run.

**Comment by jwaldrip** [comment]
@relonger sorry for the long wait here. I'm on it.
