### ISSUE TITLE
No variable named long_reg

### ISSUE THREAD

**Issue by redjohn** [jwaldrip/admiral.cr#17]
I just tried to create a flag with a long version that didn't match the regex checked [here](https://github.com/jwaldrip/admiral.cr/blob/1e42e1de55c273e0644614149feb143d5f208ea0/src/admiral/command/flag.cr#L284), and the error message references a variable that isn't defined:

```
  define_flag skip_install : Bool,
  ^~~~~~~~~~~

in lib/admiral/src/admiral/command/flag.cr:285: undefined macro variable 'long_reg'

        raise "The long flag #{@type}(#{long}) must match the regex: #{long_reg}"
                                                                       ^~~~~~~~
```

I was still able to figure out what needed to be fixed in my code, but thought you would want to know.

**Comment by jwaldrip** [comment]
fixed
