### ISSUE TITLE
Crystal 0.27.0 Upgrade

### ISSUE THREAD

**Issue by s0kil** [jwaldrip/admiral.cr#18]
This issue was created as an upgrade status for Crystal 0.27.0

**Comment by waghanza** [comment]
@DanielSokil this `shards` does not compile on `crystal` `0.27.0` ? I'm using it in https://github.com/the-benchmarker/web-frameworks

**Comment by s0kil** [comment]
No, I have tried to compile.

**Comment by waghanza** [comment]
@DanielSokil Could you give use more info ? `crystal`, `llvm`, `dist` ?

**Comment by waghanza** [comment]
@jwaldrip Can we close ?

@s0kil Still this issue ?

**Comment by s0kil** [comment]
@waghanza Good to close.
