### ISSUE TITLE
A way to say "this or this"

### ISSUE THREAD

**Issue by bararchy** [jwaldrip/admiral.cr#5]
So, I want one of two flags to be required, not both, not none, but this or the other
```
flag1
flag2

raise unless flag1 || flag2
```

This is what I use now, but it lacks "promise" that one will be required.

**Comment by jwaldrip** [comment]
@bararchy good suggestion, I will think about how to incorporate that into the DSL.

**Comment by bararchy** [comment]
Hi @jwaldrip any update? :)

**Comment by jwaldrip** [comment]
@bararchy checking in. No update on the DSL as of yet.
